#include <iostream>
#include <unordered_map>
#include <vector>
#include <utility>

// Forward declarations
// struct SW_JOIN_FULLOUTER_TD_1844_key;
// struct SW_JOIN_FULLOUTER_TD_1844_payload;
//
// // Mock-up class for Table
// class Table {
//     std::vector<std::vector<int32_t>> data;
//     public:
//         Table(int numRows, int numCols) : data(numRows, std::vector<int32_t>(numCols, -1)) {}
//
//             void setInt32(int row, int col, int32_t value) {
//                     if (row < data.size() && col < data[row].size()) {
//                                 data[row][col] = value;
//                                         }
//                                             }
//
//                                                 int32_t getInt32(int row, int col) {
//                                                         if (row < data.size() && col < data[row].size()) {
//                                                                     return data[row][col];
//                                                                             }
//                                                                                     return -1;
//                                                                                         }
//
//                                                                                             int getNumRow() {
//                                                                                                     return static_cast<int>(data.size());
//                                                                                                         }
//
//                                                                                                             void setNumRow(int numRows) {
//                                                                                                                     data.resize(numRows);
//                                                                                                                         }
//
//                                                                                                                             void print() {
//                                                                                                                                     for (const auto& row : data) {
//                                                                                                                                                 for (const auto& col : row) {
//                                                                                                                                                                 std::cout << col << " ";
//                                                                                                                                                                             }
//                                                                                                                                                                                         std::cout << std::endl;
//                                                                                                                                                                                                 }
//                                                                                                                                                                                                     }
//                                                                                                                                                                                                     };
//
//                                                                                                                                                                                                     // Custom hash function for the join key
//                                                                                                                                                                                                     struct SW_JOIN_FULLOUTER_TD_1844_key {
//                                                                                                                                                                                                         int32_t customer_sk;
//                                                                                                                                                                                                             int32_t item_sk;
//
//                                                                                                                                                                                                                 bool operator==(const SW_JOIN_FULLOUTER_TD_1844_key& other) const {
//                                                                                                                                                                                                                         return customer_sk == other.customer_sk && item_sk == other.item_sk;
//                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                             };
//
//                                                                                                                                                                                                                             namespace std {
//                                                                                                                                                                                                                                 template<> struct hash<SW_JOIN_FULLOUTER_TD_1844_key> {
//                                                                                                                                                                                                                                         size_t operator()(const SW_JOIN_FULLOUTER_TD_1844_key& k) const {
//                                                                                                                                                                                                                                                     return std::hash<int32_t>()(k.customer_sk) ^ std::hash<int32_t>()(k.item_sk);
//                                                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                                                 };
//                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                 // Structure for the join payload
//                                                                                                                                                                                                                                                                 struct SW_JOIN_FULLOUTER_TD_1844_payload {
//                                                                                                                                                                                                                                                                     int32_t customer_sk;
//                                                                                                                                                                                                                                                                         int32_t item_sk;
//                                                                                                                                                                                                                                                                         };
//
//                                                                                                                                                                                                                                                                         // Function to perform the full outer join
//                                                                                                                                                                                                                                                                         void SW_JOIN_FULLOUTER_TD_1844(Table &tbl_Aggregate_TD_2547_output, Table &tbl_Aggregate_TD_2581_output, Table &tbl_JOIN_FULLOUTER_TD_1844_output) {
//                                                                                                                                                                                                                                                                             std::unordered_map<SW_JOIN_FULLOUTER_TD_1844_key, SW_JOIN_FULLOUTER_TD_1844_payload> ht1;
//                                                                                                                                                                                                                                                                                 std::unordered_map<SW_JOIN_FULLOUTER_TD_1844_key, bool> matched;
//                                                                                                                                                                                                                                                                                     
//                                                                                                                                                                                                                                                                                         int nrow1 = tbl_Aggregate_TD_2581_output.getNumRow();
//                                                                                                                                                                                                                                                                                             int nrow2 = tbl_Aggregate_TD_2547_output.getNumRow();
//
//                                                                                                                                                                                                                                                                                                 // Populate hash table with left table's data
//                                                                                                                                                                                                                                                                                                     for (int i = 0; i < nrow1; i++) {
//                                                                                                                                                                                                                                                                                                             SW_JOIN_FULLOUTER_TD_1844_key key{
//                                                                                                                                                                                                                                                                                                                         tbl_Aggregate_TD_2581_output.getInt32(i, 0),
//                                                                                                                                                                                                                                                                                                                                     tbl_Aggregate_TD_2581_output.getInt32(i, 1)
//                                                                                                                                                                                                                                                                                                                                             };
//                                                                                                                                                                                                                                                                                                                                                     SW_JOIN_FULLOUTER_TD_1844_payload payload{
//                                                                                                                                                                                                                                                                                                                                                                 tbl_Aggregate_TD_2581_output.getInt32(i, 0),
//                                                                                                                                                                                                                                                                                                                                                                             tbl_Aggregate_TD_2581_output.getInt32(i, 1)
//                                                                                                                                                                                                                                                                                                                                                                                     };
//                                                                                                                                                                                                                                                                                                                                                                                             ht1.insert(std::make_pair(key, payload));
//                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                     // Perform left outer join
//                                                                                                                                                                                                                                                                                                                                                                                                         int r = 0;
//                                                                                                                                                                                                                                                                                                                                                                                                             for (int i = 0; i < nrow2; i++) {
//                                                                                                                                                                                                                                                                                                                                                                                                                     SW_JOIN_FULLOUTER_TD_1844_key key{
//                                                                                                                                                                                                                                                                                                                                                                                                                                 tbl_Aggregate_TD_2547_output.getInt32(i, 0),
//                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_Aggregate_TD_2547_output.getInt32(i, 1)
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     };
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             auto range = ht1.equal_range(key);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (range.first != range.second) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for (auto it = range.first; it != range.second; ++it) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tbl_JOIN_FULLOUTER_TD_1844_output.setInt32(r, 0, it->second.customer_sk);  // customer_sk#3697
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tbl_JOIN_FULLOUTER_TD_1844_output.setInt32(r, 1, key.customer_sk);         // customer_sk#3699
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 r++;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         matched[key] = true;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_JOIN_FULLOUTER_TD_1844_output.setInt32(r, 0, -1);  // customer_sk#3697
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         tbl_JOIN_FULLOUTER_TD_1844_output.setInt32(r, 1, key.customer_sk);  // customer_sk#3699
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     r++;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Add unmatched rows from the left table
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for (const auto& kv : ht1) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (!matched[kv.first]) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_JOIN_FULLOUTER_TD_1844_output.setInt32(r, 0, kv.second.customer_sk);  // customer_sk#3697
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         tbl_JOIN_FULLOUTER_TD_1844_output.setInt32(r, 1, -1);  // customer_sk#3699
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     r++;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tbl_JOIN_FULLOUTER_TD_1844_output.setNumRow(r);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         tbl_JOIN_FULLOUTER_TD_1844_output.print();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         int main() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Table tbl_Aggregate_TD_2547_output(3, 2);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Table tbl_Aggregate_TD_2581_output(3, 2);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Table tbl_JOIN_FULLOUTER_TD_1844_output(0, 2);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Example data for tbl_Aggregate_TD_2547_output (Right Table)
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_Aggregate_TD_2547_output.setInt32(0, 0, 1);  // customer_sk#3697
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tbl_Aggregate_TD_2547_output.setInt32(0, 1, 100);  // item_sk#3698
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tbl_Aggregate_TD_2547_output.setInt32(1, 0, 2);  // customer_sk#3697
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         tbl_Aggregate_TD_2547_output.setInt32(1, 1, 200);  // item_sk#3698
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_Aggregate_TD_2547_output.setInt32(2, 0, 3);  // customer_sk#3697
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tbl_Aggregate_TD_2547_output.setInt32(2, 1, 300);  // item_sk#3698
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Example data for tbl_Aggregate_TD_2581_output (Left Table)
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         tbl_Aggregate_TD_2581_output.setInt32(0, 0, 2);  // customer_sk#3699
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_Aggregate_TD_2581_output.setInt32(0, 1, 200);  // item_sk#3700
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tbl_Aggregate_TD_2581_output.setInt32(1, 0, 3);  // customer_sk#3699
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tbl_Aggregate_TD_2581_output.setInt32(1, 1, 300);  // item_sk#3700
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         tbl_Aggregate_TD_2581_output.setInt32(2, 0, 4);  // customer_sk#3699
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             tbl_Aggregate_TD_2581_output.setInt32(2, 1, 400);  // item_sk#3700
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Perform Full Outer Join
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SW_JOIN_FULLOUTER_TD_1844(tbl_Aggregate_TD_2547_output, tbl_Aggregate_TD_2581_output, tbl_JOIN_FULLOUTER_TD_1844_output);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return 0;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
